[window]
decorations = "none"
dynamic_title = true
opacity = 0.9
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10

[terminal]
osc52 = "CopyPaste"

[env]
TERM = "alacritty"

[cursor]
style = "Block"
unfocused_hollow = true

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[font]
size = 15.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ''',│`|:"' ()[]{}<>'''

[keyboard]

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml",
  "~/.config/alacritty/platform.toml"
]
