[mgr]
prepend_keymap = [
  { on = "y",            run = "noop",        desc = "" },
  { on = [ "y", "y" ], run = "yank",             desc = "Yank (copy)" },
  { on = [ "y", "p" ], run = "copy path",         desc = "Copy file path" },
  { on = [ "y", "d" ], run = "copy dirname",      desc = "Copy directory path" },
  { on = [ "y", "f" ], run = "copy filename",     desc = "Copy filename" },
  { on = [ "y", "n" ], run = "copy name_without_ext", desc = "Copy filename without ext" },
  { on = "d",           run = "noop",        desc = "" },
  { on = [ "d", "d" ], run = "yank --cut", desc = "Cut" },
  { on = [ "d", "D" ], run = "remove",    desc = "Trash" },
  { on = "l",          run = "plugin smart-enter", desc = "Enter dir or open file" },
  { on = "<Enter>",    run = "plugin smart-enter", desc = "Enter dir or open file" },
  { on = [ "g", "r" ], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"', desc = "cd to git root" },
]
