[mgr]
prepend_keymap = [
  { on = "d",           run = "noop",        desc = "" },
  { on = [ "d", "d" ], run = "yank --cut", desc = "Cut" },
  { on = "l",          run = "plugin smart-enter", desc = "Enter dir or open file" },
  { on = "<Enter>",    run = "plugin smart-enter", desc = "Enter dir or open file" },
]
