[mgr]
ratio = [1, 2, 1]
show_hidden = true

[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" },
]

[open]
prepend_rules = [
  { mime = "*/*", use = [ "edit" ] },
]

[preview]
max_width = 600
max_height = 900

[plugin]
prepend_previewers = [
  { mime = "image/*", run = "image" },
  { mime = "{audio,video}/*", run = "mediainfo" },
]
